spring.application.name=saloonX

# Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER:org.postgresql.Driver}

# Server Configuration
server.port=${PORT:7860}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=${DB_DIALECT:org.hibernate.dialect.PostgreSQLDialect}

# AI Service Configuration
deepseek.api.key=${DEEPSEEK_API_KEY}
deepseek.api.base.url=https://api.deepseek.com/chat/completions
lightx.api.key=${LIGHTX_API_KEY}
lightx.api.base.url=https://api.lightxeditor.com/external/api

# OAuth2 Configuration
app.oauth2.default-success-url=/home
app.oauth2.providers.google.client-id=${GOOGLE_CLIENT_ID}
app.oauth2.providers.google.client-secret=${GOOGLE_CLIENT_SECRET}
app.oauth2.providers.google.scope=openid,profile,email

app.oauth2.providers.facebook.client-id=${FACEBOOK_CLIENT_ID}
app.oauth2.providers.facebook.client-secret=${FACEBOOK_CLIENT_SECRET}
app.oauth2.providers.facebook.scope=public_profile

app.oauth2.providers.apple.client-id=${APPLE_CLIENT_ID}
app.oauth2.providers.apple.client-secret=${APPLE_CLIENT_SECRET}
app.oauth2.providers.apple.scope=openid,name,email
app.oauth2.providers.apple.issuer-uri=https://appleid.apple.com
